name: Deploy Terraform Infrastructure

on:
  push:
    branches: [main]

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      PROJECT_ID: b7e7fa2921e8
      AMI_ID: ami-01f3a9a49e4032afb
      PROJECT_NAME: bookstore
      DB_NAME: bookstoredb
      DB_USERNAME: bookstoredbadmin
      GITHUB_USER: jordivilagut
      DOMAIN_NAME: llibresencatala.cat
      KEY_PAIR: vitrstudio

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Retrieve environment variables from SSM
        run: .github/scripts/get_ssm_variables.sh

      - name: Retrieve or generate DB password
        run: .github/scripts/get_or_create_db_password.sh

      - name: Terraform init
        run: ../.github/scripts/terraform_init.sh
        working-directory: infra

      - name: Terraform plan
        run: ../.github/scripts/terraform_plan.sh
        working-directory: infra

      - name: Terraform apply
        run: terraform apply -auto-approve tfplan
        working-directory: infra
